import type { ExamAttemptEvidence } from "@/lib/exams";

const LOGO_URL = "https://media.base44.com/images/public/6a1117d573bbf85981b1abee/8271ac857_IMG_9226.png";

function esc(value: unknown) {
  return String(value ?? "—").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char] || char));
}

function fmtDate(value?: string | null) {
  if (!value) return "—";
  return new Date(value).toLocaleDateString("pt-BR", { timeZone: "America/Maceio" });
}

export function openAptitudeCertificate(evidence: ExamAttemptEvidence) {
  const popup = window.open("", "_blank", "width=1180,height=820");
  if (!popup) throw new Error("O navegador bloqueou a abertura do certificado");
  const rows = evidence.questions.map((question) => `<tr><td>${question.order}</td><td>${esc(question.statement)}</td><td>${esc(question.answer)}</td><td class="${question.correct ? "ok" : "bad"}">${question.correct ? "Correta" : "Incorreta"}</td></tr>`).join("");
  const status = evidence.passed ? "APTO" : "NÃO APTO";
  const signed = evidence.signed_at ? `Assinatura eletrônica registrada em ${esc(new Date(evidence.signed_at).toLocaleString("pt-BR", { timeZone: "America/Maceio" }))}` : "Sem assinatura eletrônica registrada";
  popup.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Certificado de Aptidão · SEGEMPAT</title><style>
  @page{size:A4 landscape;margin:8mm}*{box-sizing:border-box}body{margin:0;background:#ddd;font-family:Arial,sans-serif;color:#111827}.page{width:281mm;min-height:194mm;margin:8mm auto;background:#fff;border:2px solid #b8912f;padding:10mm 13mm;position:relative;page-break-after:always}.page:last-child{page-break-after:auto}.brand{display:flex;align-items:center;gap:16px;border-bottom:2px solid #C8102E;padding-bottom:8px}.brand img{height:52px;background:#fff}.brand-name{font-size:30px;font-weight:900}.brand-name b{color:#C8102E}.subtitle{color:#6b7280;font-size:12px;letter-spacing:2px;text-transform:uppercase}.title{text-align:center;margin:18px 0 4px;font-family:Georgia,serif;font-size:38px}.title span{color:#C8102E}.lead{text-align:center;max-width:920px;margin:0 auto 20px;color:#374151;font-size:15px;line-height:1.55}.panel{display:grid;grid-template-columns:1fr 1fr;gap:0;border:1px solid #d7c79b;border-radius:16px;overflow:hidden}.col{padding:18px 22px}.col+ .col{border-left:1px solid #e5e7eb}.field{margin:0 0 14px}.label{font-size:10px;font-weight:800;letter-spacing:1.3px;color:#6b7280;text-transform:uppercase}.value{font-size:17px;font-weight:800;margin-top:3px}.apt{color:#07844f}.code{font-family:monospace}.footer{display:flex;justify-content:space-between;align-items:end;margin-top:22px}.sign{width:45%;text-align:center;border-top:1px solid #9a7422;padding-top:6px;font-size:11px}.seal{width:90px;height:90px;border:4px double #b8912f;border-radius:50%;display:flex;align-items:center;justify-content:center;text-align:center;color:#8a681d;font-weight:900;font-size:11px}.evidence-title{font-size:31px;margin:14px 0 3px;text-align:center;font-family:Georgia,serif}.evidence-title span{color:#C8102E}.annex{text-align:center;color:#C8102E;font-weight:800;letter-spacing:3px;font-size:11px;margin-bottom:14px}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.metric{border:1px solid #e5e7eb;border-radius:12px;padding:10px;text-align:center;background:#f9fafb}.metric strong{display:block;font-size:22px;margin-top:4px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #d1d5db;padding:8px;vertical-align:top}th{background:#f3f4f6;text-transform:uppercase;font-size:9px;letter-spacing:.8px}.ok{color:#07844f;font-weight:800}.bad{color:#C8102E;font-weight:800}.note{margin-top:12px;border:1px solid #d7c79b;border-radius:10px;padding:10px;color:#4b5563;font-size:10px}.water{position:absolute;right:18px;bottom:12px;color:#e5e7eb;font-size:54px;font-weight:900;z-index:0}.content{position:relative;z-index:1}@media print{body{background:#fff}.page{margin:0;width:auto;min-height:0;box-shadow:none}}
  </style></head><body>
  <section class="page"><div class="content"><div class="brand"><img src="${LOGO_URL}" alt="EMPAT"><div><div class="brand-name">SEG<b>EMPAT</b></div><div class="subtitle">Segurança Portuária · Gestão, Operações e Desempenho</div></div></div><h1 class="title">CERTIFICADO DE <span>APTIDÃO</span></h1><p class="lead">A EMPAT, por meio do sistema SEGEMPAT, certifica que o colaborador abaixo identificado foi avaliado e considerado <strong>${status}</strong> para a atividade descrita, conforme o resultado registrado no sistema.</p><div class="panel"><div class="col"><div class="field"><div class="label">Nome</div><div class="value">${esc(evidence.employee_name)}</div></div><div class="field"><div class="label">Matrícula</div><div class="value">${esc(evidence.matricula)}</div></div><div class="field"><div class="label">Setor</div><div class="value">${esc(evidence.sector)}</div></div><div class="field"><div class="label">Tema / Avaliação</div><div class="value">${esc(evidence.exam_title)}</div></div></div><div class="col"><div class="field"><div class="label">Resultado</div><div class="value apt">${status}</div></div><div class="field"><div class="label">Nota</div><div class="value">${Number(evidence.score).toFixed(1)}</div></div><div class="field"><div class="label">Data da avaliação</div><div class="value">${fmtDate(evidence.finished_at)}</div></div><div class="field"><div class="label">Código de validação</div><div class="value code">${esc(evidence.certificate_code)}</div></div></div></div><div class="footer"><div class="sign"><strong>${esc(evidence.signature_name || evidence.employee_name)}</strong><br>${signed}</div><div class="seal">SEGEMPAT<br>APTIDÃO<br>REGISTRADA</div></div></div><div class="water">EMPAT</div></section>
  <section class="page"><div class="content"><div class="brand"><img src="${LOGO_URL}" alt="EMPAT"><div><div class="brand-name">SEG<b>EMPAT</b></div><div class="subtitle">Segurança Portuária · Evidência documental</div></div></div><h1 class="evidence-title">EVIDÊNCIA DA <span>AVALIAÇÃO</span></h1><div class="annex">ANEXO DO CERTIFICADO DE APTIDÃO · PÁGINA 2 DE 2</div><div class="summary"><div class="metric">Questões<strong>${evidence.total_questions}</strong></div><div class="metric">Acertos<strong>${evidence.correct_count}</strong></div><div class="metric">Aproveitamento<strong>${evidence.accuracy_pct}%</strong></div><div class="metric">Situação<strong class="apt">${status}</strong></div></div><table><thead><tr><th style="width:5%">Nº</th><th style="width:43%">Questão</th><th style="width:40%">Resposta registrada</th><th style="width:12%">Resultado</th></tr></thead><tbody>${rows}</tbody></table><div class="note"><strong>Identificação:</strong> ${esc(evidence.employee_name)} · Matrícula ${esc(evidence.matricula)} · ${esc(evidence.sector)} · <strong>Avaliação:</strong> ${esc(evidence.exam_title)} · <strong>Código:</strong> ${esc(evidence.certificate_code)}. Esta página complementa o Certificado de Aptidão e constitui registro evidenciário das respostas armazenadas pelo SEGEMPAT.</div></div><div class="water">SEGEMPAT</div></section>
  <script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`);
  popup.document.close();
}
