import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Users, BarChart3, Shield, Target, AlertTriangle, FileText, CalendarDays, ClipboardCheck, FileSpreadsheet, ChevronRight, Activity, Trophy } from "lucide-react";
import { useCurrentUser } from "@/lib/useCurrentUser";
import { employeeRisk, getOperationalSnapshot, sectorMetrics, snapshotMetrics } from "@/lib/insights";

export const Route = createFileRoute("/_authenticated/admin")({ head:()=>({meta:[{title:"Dashboard · SEGEMPAT"}]}), component:AdminDashboard });
function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <div className={`rounded-2xl ${className}`} style={{background:"var(--bg-surface)",border:"1px solid var(--border)",boxShadow:"var(--shadow-card, var(--shadow-md))"}}>{children}</div>}
function KPI({label,value,icon:Icon,sub}:{label:string;value:string|number;icon:typeof Users;sub?:string}){return <Card className="p-4 relative overflow-hidden"><div className="absolute -right-8 -top-8 w-24 h-24 rounded-full opacity-[.08]" style={{background:"var(--accent)"}}/><div className="relative flex justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.16em] font-black" style={{color:"var(--text-4)"}}>{label}</p><p className="mt-2 text-2xl font-black" style={{color:"var(--text-1)"}}>{value}</p>{sub&&<p className="mt-1 text-xs" style={{color:"var(--text-4)"}}>{sub}</p>}</div><div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{background:"var(--accent-soft)"}}><Icon className="w-4 h-4" style={{color:"var(--accent)"}}/></div></div></Card>}

function AdminDashboard(){
 const year=new Date().getFullYear(); const {data:user}=useCurrentUser(); const {data,isLoading}=useQuery({queryKey:["admin-snapshot",year],queryFn:()=>getOperationalSnapshot(year),staleTime:60_000});
 if(isLoading)return <div className="flex justify-center py-20"><div className="w-8 h-8 rounded-full border-4 animate-spin" style={{borderColor:"var(--border)",borderTopColor:"#C8102E"}}/></div>;
 if(!data)return <Card className="p-8"><p style={{color:"var(--text-3)"}}>Não foi possível carregar o dashboard.</p></Card>;
 const m=snapshotMetrics(data); const sectors=sectorMetrics(data); const risk=employeeRisk(data); const first=user?.nome?.split(" ")[0]||"Inspetor"; const h=new Date().getHours(); const greeting=h<12?"Bom dia":h<18?"Boa tarde":"Boa noite";
 const quick=[{to:"/cronograma",label:"Cronograma",icon:CalendarDays},{to:"/equipe",label:"Equipe",icon:Users},{to:"/provas",label:"Provas",icon:FileText},{to:"/avaliacao-pratica",label:"Avaliação prática",icon:ClipboardCheck},{to:"/analytics",label:"Analytics",icon:BarChart3},{to:"/relatorios",label:"Relatórios",icon:FileSpreadsheet}];
 const priorityCount=risk.filter(r=>r.score>0).length;
 const leaders=data.employees.filter(e=>e.status==="Ativo"&&e.access_profile!=="Inspetor").sort((a,b)=>b.points-a.points).slice(0,4);
 return <div className="mx-auto max-w-7xl space-y-5 pb-10">
  <div className="relative overflow-hidden rounded-[1.5rem] p-5 md:p-7" style={{background:"linear-gradient(135deg,#171118 0%,#2b0b13 48%,#101115 100%)",border:"1px solid rgba(200,16,46,.26)",boxShadow:"0 10px 34px rgba(200,16,46,.14)"}}><div className="absolute -right-24 -top-28 w-80 h-80 rounded-full" style={{background:"radial-gradient(circle,rgba(200,16,46,.24),transparent 70%)"}}/><div className="relative flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><p className="text-[11px] uppercase tracking-[.22em] font-black text-white/50">{greeting}</p><h1 className="mt-1 text-2xl md:text-3xl font-black text-white">{first}</h1><p className="mt-1 text-sm text-white/55">Visão consolidada da operação · {year}</p></div><div className="rounded-xl px-4 py-3 flex items-center gap-3" style={{background:"rgba(255,255,255,.07)",border:"1px solid rgba(255,255,255,.12)"}}><span className="w-2 h-2 rounded-full bg-green-500"/><span className="text-sm font-bold text-white/85">{m.activeEmployees} colaboradores ativos</span></div></div></div>
  <div className="grid grid-cols-2 lg:grid-cols-5 gap-3"><KPI label="Equipe ativa" value={m.activeEmployees} icon={Users}/><KPI label="Execução" value={`${m.executionRate}%`} icon={Activity} sub={`${m.realized} realizados`}/><KPI label="Aprovação" value={`${m.approvalRate}%`} icon={Shield} sub={`${m.passed} aprovações`}/><KPI label="Média provas" value={m.averageScore} icon={BarChart3} sub={`${m.attempts} tentativas`}/><KPI label="Pendências" value={m.pending} icon={AlertTriangle} sub={`${m.justified} justificadas`}/></div>
  <Card className="p-3"><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2">{quick.map(({to,label,icon:Icon})=><Link key={to} to={to as any}><div className="rounded-xl p-3 flex items-center gap-3 h-full transition-colors duration-150" style={{background:"var(--bg-surface-2)",border:"1px solid var(--border)"}}><div className="w-9 h-9 rounded-xl flex items-center justify-center shrink-0" style={{background:"var(--accent-soft)"}}><Icon className="w-4 h-4" style={{color:"var(--accent)"}}/></div><span className="text-xs font-bold" style={{color:"var(--text-2)"}}>{label}</span></div></Link>)}</div></Card>
  <div className="grid lg:grid-cols-3 gap-4">
   <Card className="lg:col-span-2 p-4"><div className="flex items-center gap-2 mb-4"><BarChart3 className="w-4 h-4" style={{color:"var(--accent)"}}/><div><h2 className="font-bold text-sm" style={{color:"var(--text-1)"}}>Execução por setor</h2><p className="text-[11px] mt-0.5" style={{color:"var(--text-4)"}}>Percentual concluído no ano</p></div></div>{sectors.length===0?<div className="py-12 text-center"><BarChart3 className="w-9 h-9 mx-auto" style={{color:"var(--text-4)"}}/><p className="mt-2 text-sm font-bold" style={{color:"var(--text-2)"}}>Sem dados por setor</p><p className="mt-1 text-xs" style={{color:"var(--text-4)"}}>Os indicadores aparecem quando houver colaboradores e lançamentos no Cronograma.</p></div>:<div className="space-y-4">{sectors.map(s=><div key={s.sector}><div className="mb-1.5 flex items-center justify-between gap-3"><span className="text-xs font-bold" style={{color:"var(--text-2)"}}>{s.sector}</span><span className="text-xs font-black" style={{color:s.executionRate>=80?"#10b981":s.executionRate>=50?"#f59e0b":"var(--accent)"}}>{s.executionRate}%</span></div><div className="h-2.5 overflow-hidden rounded-full" style={{background:"var(--bg-surface-2)",border:"1px solid var(--border-subtle)"}}><div className="h-full rounded-full transition-[width] duration-300" style={{width:`${Math.max(0,Math.min(100,s.executionRate))}%`,background:s.executionRate>=80?"linear-gradient(90deg,#059669,#10b981)":s.executionRate>=50?"linear-gradient(90deg,#d97706,#f59e0b)":"linear-gradient(90deg,#9f1239,#C8102E)"}}/></div><div className="mt-1 flex justify-between text-[10px]" style={{color:"var(--text-4)"}}><span>{s.realized}/{s.planned} realizados</span><span>{s.employees} colaborador{s.employees===1?"":"es"}</span></div></div>)}</div>}</Card>
   <Card className="overflow-hidden"><div className="p-4 flex items-center gap-2" style={{borderBottom:"1px solid var(--border)"}}><AlertTriangle className="w-4 h-4 text-amber-500"/><h2 className="font-bold text-sm" style={{color:"var(--text-1)"}}>Prioridades</h2><span className="ml-auto text-xs font-black" style={{color:"var(--accent)"}}>{priorityCount}</span></div><div className="p-3 space-y-2 max-h-[260px] overflow-y-auto">{risk.filter(r=>r.score>0).slice(0,6).map(r=><div key={r.employee.id} className="rounded-xl p-3" style={{background:"var(--bg-surface-2)"}}><div className="flex justify-between gap-2"><div><p className="font-semibold text-sm" style={{color:"var(--text-1)"}}>{r.employee.full_name}</p><p className="text-xs mt-1" style={{color:"var(--text-4)"}}>{r.employee.sector}</p></div><span className="text-[10px] font-black" style={{color:r.level==="Alto"?"#ef4444":r.level==="Médio"?"#f59e0b":"#60a5fa"}}>{r.level}</span></div></div>)}{priorityCount===0&&<div className="py-8 text-center"><Shield className="w-9 h-9 mx-auto text-emerald-500"/><p className="mt-2 text-sm font-bold text-emerald-500">Sem alertas relevantes</p></div>}</div><div className="px-4 pb-4"><Link to="/risco" className="flex items-center gap-1 text-xs font-bold" style={{color:"var(--accent)"}}>Ver zona de risco <ChevronRight className="w-3 h-3"/></Link></div></Card>
  </div>
  <Card className="overflow-hidden"><div className="p-4 flex items-center gap-2" style={{borderBottom:"1px solid var(--border)"}}><Trophy className="w-4 h-4 text-amber-500"/><h2 className="font-bold text-sm" style={{color:"var(--text-1)"}}>Destaques da equipe</h2></div>{leaders.length===0?<div className="p-8 text-center"><Trophy className="w-8 h-8 mx-auto" style={{color:"var(--text-4)"}}/><p className="mt-2 text-sm font-bold" style={{color:"var(--text-2)"}}>Sem ranking disponível</p><p className="mt-1 text-xs" style={{color:"var(--text-4)"}}>O ranking aparece quando operadores acumularem pontos.</p></div>:<div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-2 p-3">{leaders.map((e,i)=><div key={e.id} className="rounded-xl p-3 flex items-center gap-3" style={{background:"var(--bg-surface-2)"}}><div className="text-xl">{["🥇","🥈","🥉","4º"][i]}</div><div className="min-w-0"><p className="font-semibold text-sm truncate" style={{color:"var(--text-1)"}}>{e.full_name}</p><p className="text-xs mt-1" style={{color:"var(--text-4)"}}>{e.points||0} pts · {e.sector}</p></div></div>)}</div>}</Card>
 </div>
}