import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FileText, PlusCircle, Trash2, Send, Undo2, Calendar, Target, PlayCircle, CheckCircle2 } from "lucide-react";
import { toast } from "sonner";
import { listExams, deleteExam, updateExam, fmtDate, type Exam } from "@/lib/exams";
import { useCurrentUser } from "@/lib/useCurrentUser";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";

export const Route = createFileRoute("/_authenticated/provas")({ head:()=>({meta:[{title:"Provas · SEGEMPAT"}]}), component:ProvasPage });

function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <div className={`rounded-2xl ${className}`} style={{background:"var(--bg-surface)",border:"1px solid var(--border)",boxShadow:"var(--shadow-card, var(--shadow-md))"}}>{children}</div>}
function Chip({children}:{children:React.ReactNode}){return <span className="text-[10px] font-semibold px-2 py-1 rounded-full" style={{background:"var(--bg-surface-3)",border:"1px solid var(--border)",color:"var(--text-3)"}}>{children}</span>}

function ProvasPage(){
  const navigate=useNavigate(); const qc=useQueryClient(); const {data:user}=useCurrentUser(); const isAdmin=user?.isAdmin??false; const [toDelete,setToDelete]=useState<string|null>(null);
  const {data:all=[],isLoading}=useQuery({queryKey:["exams"],queryFn:listExams}); const exams=isAdmin?all:all.filter(e=>e.status==="Publicada");
  const invalidate=()=>qc.invalidateQueries({queryKey:["exams"]});
  const remove=useMutation({mutationFn:deleteExam,onSuccess:()=>{toast.success("Prova excluída");setToDelete(null);invalidate()},onError:(e:Error)=>toast.error(e.message)});
  const toggle=useMutation({mutationFn:({id,status}:{id:string;status:string})=>updateExam(id,{status}),onSuccess:()=>{toast.success("Situação atualizada");invalidate()},onError:(e:Error)=>toast.error(e.message)});
  if(isLoading)return <div className="flex justify-center py-20"><div className="w-8 h-8 rounded-full border-4 animate-spin" style={{borderColor:"var(--border)",borderTopColor:"#C8102E"}}/></div>;
  return <div className="mx-auto max-w-5xl space-y-5 pb-10"><div className="rounded-[1.5rem] p-5 md:p-6 flex flex-col md:flex-row md:items-end md:justify-between gap-4" style={{background:"linear-gradient(135deg,#171118,#2b0b13 50%,#111216)",border:"1px solid rgba(200,16,46,.26)"}}><div><div className="flex items-center gap-2 text-[11px] uppercase tracking-[.2em] font-black text-white/40"><FileText className="w-4 h-4"/> Avaliações</div><h1 className="mt-2 text-2xl md:text-3xl font-black text-white">Provas</h1><p className="mt-1 text-sm text-white/50">{isAdmin?"Crie, publique e acompanhe provas.":"Realize as provas publicadas para seu perfil."}</p></div>{isAdmin&&<button onClick={()=>navigate({to:"/provas-criar"})} className="h-10 px-4 rounded-xl flex items-center gap-2 font-bold text-sm text-white bg-[#C8102E]"><PlusCircle className="w-4 h-4"/> Nova prova</button>}</div>
    {exams.length===0?<Card className="p-10 text-center"><CheckCircle2 className="w-10 h-10 mx-auto opacity-30" style={{color:"var(--text-4)"}}/><p className="mt-3 font-bold" style={{color:"var(--text-1)"}}>{isAdmin?"Nenhuma prova cadastrada.":"Nenhuma prova publicada disponível."}</p></Card>:<div className="space-y-3">{exams.map((exam:Exam)=><Card key={exam.id} className="overflow-hidden"><div className="h-[3px]" style={{background:exam.status==="Publicada"?"#10b981":"#f59e0b"}}/><div className="p-4 md:p-5"><div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold" style={{color:"var(--text-1)"}}>{exam.title}</h3><span className="text-[10px] font-black" style={{color:exam.status==="Publicada"?"#10b981":"#f59e0b"}}>{exam.status}</span></div>{exam.description&&<p className="mt-2 text-sm" style={{color:"var(--text-3)"}}>{exam.description}</p>}<div className="mt-3 flex flex-wrap gap-2"><Chip>{exam.exam_type}</Chip><Chip>{exam.questions.length} questões</Chip><Chip>Mín. {exam.min_approval_pct}%</Chip><Chip><Target className="inline w-3 h-3 mr-1"/>{exam.target_sector}</Chip><Chip><Calendar className="inline w-3 h-3 mr-1"/>{fmtDate(exam.scheduled_date)}</Chip></div></div><div className="flex flex-wrap gap-2 shrink-0">{isAdmin?<><Link to="/provas-criar" search={{id:exam.id}} className="h-9 px-3 rounded-lg inline-flex items-center text-xs font-bold" style={{border:"1px solid var(--border)",color:"var(--text-2)"}}>Editar</Link><button onClick={()=>toggle.mutate({id:exam.id,status:exam.status==="Publicada"?"Rascunho":"Publicada"})} className="h-9 px-3 rounded-lg inline-flex items-center gap-1.5 text-xs font-bold" style={{border:"1px solid var(--border)",color:"var(--text-2)"}}>{exam.status==="Publicada"?<Undo2 className="w-3.5 h-3.5"/>:<Send className="w-3.5 h-3.5"/>}{exam.status==="Publicada"?"Despublicar":"Publicar"}</button><button onClick={()=>setToDelete(exam.id)} className="h-9 w-9 rounded-lg inline-flex items-center justify-center text-red-500" style={{border:"1px solid var(--border)"}}><Trash2 className="w-4 h-4"/></button></>:<button onClick={()=>navigate({to:"/prova-realizar",search:{id:exam.id}})} className="h-10 px-4 rounded-xl flex items-center gap-2 font-bold text-sm text-white bg-[#C8102E]"><PlayCircle className="w-4 h-4"/> Realizar prova</button>}</div></div></div></Card>)}</div>}
    <AlertDialog open={!!toDelete} onOpenChange={(o)=>!o&&setToDelete(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir prova?</AlertDialogTitle><AlertDialogDescription>As tentativas relacionadas também serão removidas. Esta ação não pode ser desfeita.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction className="bg-[#C8102E] hover:bg-[#A00D24]" onClick={()=>toDelete&&remove.mutate(toDelete)}>Excluir</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>
}
