import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ClipboardCheck, ChevronLeft, ChevronRight, CheckCircle2, AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getExam, saveAttempt } from "@/lib/exams";
import { useCurrentUser } from "@/lib/useCurrentUser";
import { syncCronogramaWithExamAttempts } from "@/lib/cronograma";

export const Route = createFileRoute("/_authenticated/prova-realizar")({
  validateSearch: (search: Record<string, unknown>) => ({ id: typeof search["id"] === "string" ? search["id"] : "" }),
  head: () => ({ meta: [{ title: "Realizar Prova · SEGEMPAT" }] }),
  component: TakeExamPage,
});

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={`rounded-2xl ${className}`} style={{ background:"var(--bg-surface)",border:"1px solid var(--border)",boxShadow:"var(--shadow-card, var(--shadow-md))" }}>{children}</div>; }
function normalize(s: string) { return s.trim().toLocaleLowerCase("pt-BR").replace(/\s+/g," "); }

function TakeExamPage() {
  const { id } = Route.useSearch(); const navigate = useNavigate(); const { data:user } = useCurrentUser();
  const { data:exam,isLoading,isError } = useQuery({queryKey:["exam",id],queryFn:()=>getExam(id),enabled:!!id});
  const [index,setIndex]=useState(0); const [answers,setAnswers]=useState<Record<string,number|string>>({}); const [finished,setFinished]=useState<{score:number;percent:number;passed:boolean}|null>(null); const [saving,setSaving]=useState(false);
  const question=exam?.questions[index]; const answered=exam?exam.questions.filter(q=>answers[q.id]!==undefined&&String(answers[q.id]).trim()!=="").length:0;
  const totalPoints=useMemo(()=>exam?.questions.reduce((s,q)=>s+Math.max(1,Number(q.points||1)),0)||0,[exam]);
  if(isLoading)return <div className="flex justify-center py-20"><div className="w-8 h-8 rounded-full border-4 animate-spin" style={{borderColor:"var(--border)",borderTopColor:"#C8102E"}}/></div>;
  if(isError||!exam||exam.status!=="Publicada")return <Card className="mx-auto max-w-2xl p-10 text-center"><AlertTriangle className="w-10 h-10 mx-auto text-amber-500"/><p className="mt-3 font-bold" style={{color:"var(--text-1)"}}>Prova indisponível.</p><Button className="mt-4" variant="outline" onClick={()=>navigate({to:"/provas"})}>Voltar</Button></Card>;
  const finish=async()=>{if(answered<exam.questions.length&&!confirm(`Você respondeu ${answered} de ${exam.questions.length} questões. Deseja finalizar mesmo assim?`))return;let earned=0;for(const q of exam.questions){const pts=Math.max(1,Number(q.points||1));const a=answers[q.id];if(q.type==="Múltipla escolha"){if(Number(a)===Number(q.correct_index))earned+=pts;}else if(q.model_answer&&typeof a==="string"&&normalize(a)===normalize(q.model_answer)){earned+=pts;}}const percent=totalPoints?Math.round(earned/totalPoints*100):0;const score=Math.round((percent/10)*10)/10;const passed=percent>=Number(exam.min_approval_pct||70);setSaving(true);try{const {data:auth}=await (await import("@/integrations/supabase/client")).supabase.auth.getUser();if(!auth.user)throw new Error("Sessão inválida");await saveAttempt({exam_id:exam.id,user_id:auth.user.id,matricula:user?.matricula||null,score,passed,answers});await syncCronogramaWithExamAttempts();setFinished({score,percent,passed});}catch(e:any){alert(e.message||"Não foi possível salvar a prova");}finally{setSaving(false);}};
  if(finished)return <div className="mx-auto max-w-2xl space-y-5 pb-10"><div className="rounded-[1.5rem] p-7 text-center" style={{background:"linear-gradient(135deg,#171118,#2b0b13 50%,#111216)",border:"1px solid rgba(200,16,46,.26)"}}>{finished.passed?<CheckCircle2 className="w-12 h-12 mx-auto text-emerald-500"/>:<AlertTriangle className="w-12 h-12 mx-auto text-red-500"/>}<h1 className="mt-4 text-2xl font-black text-white">{finished.passed?"Aprovado":"Não aprovado"}</h1><p className="mt-2 text-white/50">Resultado registrado no SEGEMPAT.</p></div><div className="grid grid-cols-3 gap-3"><Card className="p-4 text-center"><p className="text-[10px] uppercase font-black" style={{color:"var(--text-4)"}}>Nota</p><p className="mt-2 text-2xl font-black" style={{color:"var(--text-1)"}}>{finished.score}</p></Card><Card className="p-4 text-center"><p className="text-[10px] uppercase font-black" style={{color:"var(--text-4)"}}>Percentual</p><p className="mt-2 text-2xl font-black" style={{color:"var(--text-1)"}}>{finished.percent}%</p></Card><Card className="p-4 text-center"><p className="text-[10px] uppercase font-black" style={{color:"var(--text-4)"}}>Mínimo</p><p className="mt-2 text-2xl font-black" style={{color:"var(--text-1)"}}>{exam.min_approval_pct}%</p></Card></div><Button className="w-full bg-[#C8102E] hover:bg-[#A00D24] text-white" onClick={()=>navigate({to:"/progresso"})}>Ver meu progresso</Button></div>;
  return <div className="mx-auto max-w-3xl space-y-5 pb-10"><div className="rounded-[1.5rem] p-5 md:p-6" style={{background:"linear-gradient(135deg,#171118,#2b0b13 50%,#111216)",border:"1px solid rgba(200,16,46,.26)"}}><div className="flex items-center gap-2 text-[11px] uppercase tracking-[.2em] font-black text-white/40"><ClipboardCheck className="w-4 h-4"/> Avaliação</div><h1 className="mt-2 text-xl md:text-2xl font-black text-white">{exam.title}</h1><p className="mt-1 text-sm text-white/50">Questão {index+1} de {exam.questions.length} · {answered} respondida(s)</p><div className="mt-4 h-2 rounded-full overflow-hidden bg-white/10"><div className="h-full rounded-full bg-[#C8102E]" style={{width:`${exam.questions.length?((index+1)/exam.questions.length)*100:0}%`}}/></div></div>
    <Card className="p-5 md:p-6"><p className="text-[10px] uppercase font-black tracking-[.16em]" style={{color:"var(--accent)"}}>Questão {index+1} · {question?.points||1} ponto(s)</p><h2 className="mt-3 text-base md:text-lg font-bold leading-relaxed" style={{color:"var(--text-1)"}}>{question?.statement}</h2>{question?.type==="Múltipla escolha"?<div className="mt-5 space-y-2">{question.options.map((opt,oi)=><button key={oi} onClick={()=>setAnswers({...answers,[question.id]:oi})} className="w-full text-left p-4 rounded-xl transition-all" style={answers[question.id]===oi?{background:"var(--accent-soft)",border:"1px solid rgba(200,16,46,.3)",color:"var(--text-1)"}:{background:"var(--bg-surface-2)",border:"1px solid var(--border)",color:"var(--text-2)"}}><span className="font-black mr-3">{String.fromCharCode(65+oi)}</span>{opt}</button>)}</div>:<textarea className="mt-5 w-full min-h-36 rounded-xl p-3 text-sm" style={{background:"var(--bg-surface-2)",border:"1px solid var(--border)",color:"var(--text-1)"}} value={String(answers[question?.id]??"")} onChange={(e)=>question&&setAnswers({...answers,[question.id]:e.target.value})} placeholder="Digite sua resposta..."/>}</Card>
    <div className="flex items-center justify-between gap-3"><Button variant="outline" disabled={index===0} onClick={()=>setIndex(i=>i-1)}><ChevronLeft className="w-4 h-4 mr-2"/>Anterior</Button>{index<exam.questions.length-1?<Button className="bg-[#C8102E] hover:bg-[#A00D24] text-white" onClick={()=>setIndex(i=>i+1)}>Próxima<ChevronRight className="w-4 h-4 ml-2"/></Button>:<Button className="bg-[#C8102E] hover:bg-[#A00D24] text-white" disabled={saving} onClick={finish}>{saving?"Salvando...":"Finalizar prova"}</Button>}</div>
  </div>;
}
