import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { FileSpreadsheet, Download, Users, CheckCircle2, Target, BarChart3 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getOperationalSnapshot, sectorMetrics, snapshotMetrics } from "@/lib/insights";

export const Route = createFileRoute("/_authenticated/relatorios")({ head: () => ({ meta: [{ title: "Relatórios · SEGEMPAT" }] }), component: ReportsPage });

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={`rounded-2xl ${className}`} style={{ background: "var(--bg-surface)", border: "1px solid var(--border)", boxShadow: "var(--shadow-card, var(--shadow-md))" }}>{children}</div>; }

function csvCell(value: unknown) { const s = String(value ?? ""); return `"${s.replaceAll('"','""')}"`; }

function ReportsPage() {
  const year = new Date().getFullYear();
  const { data, isLoading } = useQuery({ queryKey: ["reports-snapshot", year], queryFn: () => getOperationalSnapshot(year) });
  if (isLoading) return <div className="flex justify-center py-20"><div className="w-8 h-8 rounded-full border-4 animate-spin" style={{ borderColor: "var(--border)", borderTopColor: "#C8102E" }} /></div>;
  if (!data) return <Card className="p-8"><p style={{ color: "var(--text-3)" }}>Não foi possível carregar o relatório.</p></Card>;
  const m = snapshotMetrics(data); const sectors = sectorMetrics(data);
  const exportCsv = () => { const lines = [["Setor","Colaboradores","Planejados","Realizados","Execução %","Tentativas","Aprovação %"], ...sectors.map((s) => [s.sector,s.employees,s.planned,s.realized,s.executionRate,s.attempts,s.approvalRate])].map((r) => r.map(csvCell).join(";")); const blob = new Blob(["\ufeff" + lines.join("\n")], { type: "text/csv;charset=utf-8" }); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = `SEGEMPAT_Relatorio_${year}.csv`; a.click(); URL.revokeObjectURL(a.href); };
  return <div className="mx-auto max-w-6xl space-y-5 pb-10"><div className="rounded-[1.5rem] p-5 md:p-6 flex flex-col md:flex-row md:items-end md:justify-between gap-4" style={{ background: "linear-gradient(135deg,#171118,#2b0b13 50%,#111216)", border: "1px solid rgba(200,16,46,.26)" }}><div><div className="flex items-center gap-2 text-[11px] uppercase tracking-[.2em] font-black text-white/40"><FileSpreadsheet className="w-4 h-4" /> Consolidação operacional</div><h1 className="mt-2 text-2xl md:text-3xl font-black text-white">Relatórios</h1><p className="mt-1 text-sm text-white/50">Resumo anual de equipe, provas e cronograma.</p></div><Button onClick={exportCsv} className="bg-[#C8102E] hover:bg-[#A00D24] text-white"><Download className="w-4 h-4 mr-2" /> Exportar CSV</Button></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[["Equipe ativa",m.activeEmployees,Users],["Execução",`${m.executionRate}%`,Target],["Aprovação",`${m.approvalRate}%`,CheckCircle2],["Média provas",m.averageScore,BarChart3]].map(([l,v,I]: any) => <Card key={l} className="p-4"><div className="flex justify-between"><div><p className="text-[10px] uppercase font-black tracking-[.14em]" style={{ color: "var(--text-4)" }}>{l}</p><p className="mt-2 text-2xl font-black" style={{ color: "var(--text-1)" }}>{v}</p></div><I className="w-4 h-4" style={{ color: "var(--accent)" }} /></div></Card>)}</div>
    <Card className="overflow-hidden"><div className="p-4" style={{ borderBottom: "1px solid var(--border)" }}><h2 className="font-bold text-sm" style={{ color: "var(--text-1)" }}>Indicadores por setor</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr style={{ color: "var(--text-4)" }}><th className="text-left p-3">Setor</th><th className="text-right p-3">Equipe</th><th className="text-right p-3">Planejados</th><th className="text-right p-3">Realizados</th><th className="text-right p-3">Execução</th><th className="text-right p-3">Aprovação</th></tr></thead><tbody>{sectors.map((s) => <tr key={s.sector} style={{ borderTop: "1px solid var(--border)" }}><td className="p-3 font-semibold" style={{ color: "var(--text-1)" }}>{s.sector}</td><td className="p-3 text-right" style={{ color: "var(--text-3)" }}>{s.employees}</td><td className="p-3 text-right" style={{ color: "var(--text-3)" }}>{s.planned}</td><td className="p-3 text-right" style={{ color: "var(--text-3)" }}>{s.realized}</td><td className="p-3 text-right font-bold text-emerald-500">{s.executionRate}%</td><td className="p-3 text-right font-bold" style={{ color: "var(--accent)" }}>{s.approvalRate}%</td></tr>)}</tbody></table></div></Card>
    <Card className="p-4"><h2 className="font-bold text-sm" style={{ color: "var(--text-1)" }}>Volume consolidado</h2><div className="mt-4 grid grid-cols-2 md:grid-cols-5 gap-3 text-center">{[["Planejados",m.planned],["Realizados",m.realized],["Pendentes",m.pending],["Justificados",m.justified],["Tentativas",m.attempts]].map(([l,v]) => <div key={String(l)} className="rounded-xl p-3" style={{ background: "var(--bg-surface-2)" }}><p className="font-black text-xl" style={{ color: "var(--text-1)" }}>{v}</p><p className="text-[10px] uppercase mt-1" style={{ color: "var(--text-4)" }}>{l}</p></div>)}</div></Card>
  </div>;
}
