import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ClipboardCheck, Plus, Search, CheckCircle2, Clock3, PlayCircle, Trash2, Pencil, Award } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useCurrentUser } from "@/lib/useCurrentUser";
import { listEmployees } from "@/lib/employees";
import { createPracticalEvaluation, deletePracticalEvaluation, listPracticalEvaluations, updatePracticalEvaluation, type PracticalEvaluation } from "@/lib/operations";

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={`rounded-2xl ${className}`} style={{ background:"var(--bg-surface)",border:"1px solid var(--border)",boxShadow:"var(--shadow-card, var(--shadow-md))" }}>{children}</div>; }
const defaultChecklist = ["Apresentação e postura profissional","Comunicação operacional","Execução do procedimento","Uso correto dos recursos","Cumprimento das normas de segurança"].map((label,i)=>({id:String(i+1),label,done:false}));

export function PracticalWorkspace({ operatorTitle=false }: { operatorTitle?: boolean }) {
  const qc=useQueryClient(); const {data:user}=useCurrentUser(); const isAdmin=user?.isAdmin??false;
  const [search,setSearch]=useState(""); const [status,setStatus]=useState("Todos"); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<PracticalEvaluation|null>(null);
  const [form,setForm]=useState({employee_id:"",title:"Avaliação Prática Operacional",evaluation_date:new Date().toISOString().slice(0,10),status:"Planejada",score:0,max_score:10,notes:"",checklist:defaultChecklist});
  const query=useQuery({queryKey:["practical-evaluations"],queryFn:listPracticalEvaluations}); const employees=useQuery({queryKey:["employees"],queryFn:listEmployees,enabled:isAdmin});
  const rows=query.data??[]; const filtered=useMemo(()=>rows.filter((r)=>{if(status!=="Todos"&&r.status!==status)return false;const q=search.toLowerCase().trim();return !q||[r.employee_name,r.employee_matricula,r.employee_sector,r.title].some(v=>v.toLowerCase().includes(q));}),[rows,search,status]);
  const invalidate=()=>qc.invalidateQueries({queryKey:["practical-evaluations"]});
  const reset=()=>setForm({employee_id:"",title:"Avaliação Prática Operacional",evaluation_date:new Date().toISOString().slice(0,10),status:"Planejada",score:0,max_score:10,notes:"",checklist:defaultChecklist});
  const save=useMutation({mutationFn:async()=>{if(!form.title.trim())throw new Error("Informe o título");if(editing){await updatePracticalEvaluation(editing.id,{title:form.title,status:form.status as any,score:Number(form.score),max_score:Number(form.max_score),notes:form.notes||null,evaluation_date:form.evaluation_date||null,checklist:form.checklist,completed_at:form.status==="Concluída"?new Date().toISOString():null} as any);return;}const emp=(employees.data??[]).find(e=>e.id===form.employee_id);if(!emp)throw new Error("Selecione o colaborador");await createPracticalEvaluation({employee_id:emp.id,employee_name:emp.full_name,employee_matricula:emp.matricula,employee_sector:emp.sector,title:form.title,evaluator_name:user?.nome||null,evaluation_date:form.evaluation_date||null,checklist:form.checklist,notes:form.notes||null});},onSuccess:()=>{toast.success(editing?"Avaliação atualizada":"Avaliação planejada");setOpen(false);setEditing(null);reset();invalidate();},onError:(e:Error)=>toast.error(e.message)});
  const remove=useMutation({mutationFn:deletePracticalEvaluation,onSuccess:()=>{toast.success("Avaliação excluída");invalidate();},onError:(e:Error)=>toast.error(e.message)});
  const openEdit=(r:PracticalEvaluation)=>{setEditing(r);setForm({employee_id:r.employee_id,title:r.title,evaluation_date:r.evaluation_date||"",status:r.status,score:r.score,max_score:r.max_score,notes:r.notes||"",checklist:r.checklist.length?r.checklist:defaultChecklist});setOpen(true);};
  const counts={planned:rows.filter(r=>r.status==="Planejada").length,running:rows.filter(r=>r.status==="Em andamento").length,done:rows.filter(r=>r.status==="Concluída").length};

  if (query.isLoading) return <div className="flex justify-center py-20"><div className="h-8 w-8 animate-spin rounded-full border-4" style={{borderColor:"var(--border)",borderTopColor:"#C8102E"}}/></div>;
  if (query.isError) return <div className="mx-auto max-w-2xl rounded-2xl p-8 text-center" style={{background:"var(--bg-surface)",border:"1px solid var(--border)"}}><p className="font-bold text-red-500">Não foi possível carregar as avaliações práticas.</p><Button variant="outline" className="mt-4" onClick={()=>query.refetch()}>Tentar novamente</Button></div>;

  return <div className="mx-auto max-w-6xl space-y-5 pb-10"><div className="rounded-[1.5rem] p-5 md:p-6 flex flex-col md:flex-row md:items-end md:justify-between gap-4" style={{background:"linear-gradient(135deg,#171118,#2b0b13 50%,#111216)",border:"1px solid rgba(200,16,46,.26)"}}><div><div className="flex items-center gap-2 text-[11px] uppercase tracking-[.2em] font-black text-white/40"><ClipboardCheck className="w-4 h-4"/> Competência operacional</div><h1 className="mt-2 text-2xl md:text-3xl font-black text-white">{operatorTitle?"Minha Avaliação Prática":"Avaliação Prática"}</h1><p className="mt-1 text-sm text-white/50">Planejamento, checklist, nota e conclusão em um único fluxo.</p></div>{isAdmin&&<Button onClick={()=>{setEditing(null);reset();setOpen(true)}} className="w-full bg-[#C8102E] hover:bg-[#A00D24] text-white md:w-auto"><Plus className="w-4 h-4 mr-2"/> Planejar avaliação</Button>}</div>
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">{[["Planejadas",counts.planned,Clock3,"#f59e0b"],["Em andamento",counts.running,PlayCircle,"#60a5fa"],["Concluídas",counts.done,CheckCircle2,"#10b981"]].map(([l,v,I,c]:any)=><Card key={l} className="p-4"><div className="flex justify-between"><div><p className="text-[10px] uppercase font-black" style={{color:"var(--text-4)"}}>{l}</p><p className="mt-2 text-2xl font-black" style={{color:"var(--text-1)"}}>{v}</p></div><I className="w-4 h-4" style={{color:c}}/></div></Card>)}</div>
    <Card className="p-4"><div className="grid md:grid-cols-[1fr_190px] gap-3"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4" style={{color:"var(--text-4)"}}/><Input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Buscar colaborador ou avaliação..." className="pl-10"/></div><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["Todos","Planejada","Em andamento","Concluída"].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div></Card>
    <div className="space-y-3">{filtered.map(r=>{const pct=Math.round((Number(r.score)/Number(r.max_score||10))*100);return <Card key={r.id} className="overflow-hidden"><div className="h-[3px]" style={{background:r.status==="Concluída"?"#10b981":r.status==="Em andamento"?"#60a5fa":"#f59e0b"}}/><div className="p-4 md:p-5"><div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2 items-center"><p className="font-bold break-words" style={{color:"var(--text-1)"}}>{r.employee_name}</p><span className="text-[10px] font-black" style={{color:r.status==="Concluída"?"#10b981":r.status==="Em andamento"?"#60a5fa":"#f59e0b"}}>{r.status}</span></div><p className="text-xs mt-1 break-words" style={{color:"var(--text-4)"}}>Mat. {r.employee_matricula} · {r.employee_sector}</p><p className="mt-3 text-sm font-semibold break-words" style={{color:"var(--text-2)"}}>{r.title}</p><p className="mt-1 text-xs" style={{color:"var(--text-4)"}}>Data: {r.evaluation_date?new Date(`${r.evaluation_date}T00:00:00`).toLocaleDateString("pt-BR"):"—"}</p><div className="mt-3 flex flex-wrap gap-2">{r.checklist.map(i=><span key={i.id} className="text-[10px] px-2 py-1 rounded-full" style={{color:i.done?"#10b981":"var(--text-4)",background:i.done?"rgba(16,185,129,.1)":"var(--bg-surface-3)"}}>{i.done?"✓ ":"○ "}{i.label}</span>)}</div>{r.status==="Concluída"&&<div className="mt-4 flex items-center gap-3"><Award className="w-4 h-4" style={{color:pct>=70?"#10b981":"#ef4444"}}/><span className="font-black" style={{color:pct>=70?"#10b981":"#ef4444"}}>{r.score}/{r.max_score} · {pct}%</span></div>}{r.notes&&<p className="mt-3 text-xs break-words" style={{color:"var(--text-4)"}}>{r.notes}</p>}</div>{isAdmin&&<div className="flex w-full gap-2 md:w-auto"><Button size="sm" variant="outline" className="flex-1 md:flex-none" onClick={()=>openEdit(r)}><Pencil className="w-3.5 h-3.5 mr-1.5"/> Avaliar</Button><Button size="icon" variant="outline" className="text-red-500" onClick={()=>remove.mutate(r.id)}><Trash2 className="w-4 h-4"/></Button></div>}</div></div></Card>})}{!filtered.length&&<Card className="p-10 text-center"><ClipboardCheck className="w-10 h-10 mx-auto opacity-30" style={{color:"var(--text-4)"}}/><p className="mt-3 font-bold" style={{color:"var(--text-1)"}}>Nenhuma avaliação encontrada.</p></Card>}</div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="sm:max-w-2xl max-h-[92vh] overflow-y-auto"><DialogHeader><DialogTitle>{editing?"Avaliar colaborador":"Planejar avaliação"}</DialogTitle></DialogHeader><div className="space-y-4">{!editing&&<div className="space-y-1.5"><Label>Colaborador *</Label><Select value={form.employee_id} onValueChange={(v)=>setForm({...form,employee_id:v})}><SelectTrigger><SelectValue placeholder="Selecione..."/></SelectTrigger><SelectContent>{(employees.data??[]).filter(e=>e.status==="Ativo"&&e.access_profile!=="Inspetor").map(e=><SelectItem key={e.id} value={e.id}>{e.full_name} · {e.matricula} · {e.sector}</SelectItem>)}</SelectContent></Select></div>}<div className="grid md:grid-cols-2 gap-3"><div className="space-y-1.5"><Label>Título</Label><Input value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/></div><div className="space-y-1.5"><Label>Data</Label><Input type="date" value={form.evaluation_date} onChange={(e)=>setForm({...form,evaluation_date:e.target.value})}/></div></div>{editing&&<><div className="grid md:grid-cols-3 gap-3"><div className="space-y-1.5"><Label>Situação</Label><Select value={form.status} onValueChange={(v)=>setForm({...form,status:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["Planejada","Em andamento","Concluída"].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label>Nota</Label><Input type="number" min={0} max={form.max_score} value={form.score} onChange={(e)=>setForm({...form,score:Number(e.target.value)})}/></div><div className="space-y-1.5"><Label>Nota máxima</Label><Input type="number" min={1} value={form.max_score} onChange={(e)=>setForm({...form,max_score:Number(e.target.value)})}/></div></div><div className="space-y-2"><Label>Checklist</Label>{form.checklist.map((i,idx)=><label key={i.id} className="flex items-center gap-3 p-3 rounded-xl cursor-pointer" style={{background:i.done?"rgba(16,185,129,.08)":"var(--bg-surface-2)",border:"1px solid var(--border)"}}><input type="checkbox" checked={i.done} onChange={()=>setForm({...form,checklist:form.checklist.map((x,j)=>j===idx?{...x,done:!x.done}:x)})}/><span className="text-sm" style={{color:"var(--text-2)"}}>{i.label}</span></label>)}</div></>}<div className="space-y-1.5"><Label>Observações</Label><textarea value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})} className="w-full min-h-24 rounded-xl p-3 text-sm" style={{background:"var(--bg-surface-2)",border:"1px solid var(--border)",color:"var(--text-1)"}}/></div></div><DialogFooter className="flex-col-reverse gap-2 sm:flex-row"><Button variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button onClick={()=>save.mutate()} disabled={save.isPending} className="bg-[#C8102E] hover:bg-[#A00D24] text-white">{save.isPending?"Salvando...":"Salvar"}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
